version: '3'

services:
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
      #POSTGRES_DB: symfony-guestbook
    ports: [ "5432" ]

